import test from 'node:test';
import assert from 'node:assert/strict';
import {recoverRead,currentSid} from '../lib/session-recovery.js';
import {summarizeScanTiming} from '../lib/scan-debug.js';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
function fixture(){const root={scanAuth:{user:'test'}};let renewals=0;const calls=[];return {root,calls,get renewals(){return renewals;},args:{root,session:{sid:'old'},command:'show-task',body:{},expired:()=>true,checkCancelled(){},request:async(s,c)=>{calls.push([s.sid,c]);if(s.sid==='old')throw Error('expired');return {ok:true};},renew:async()=>{renewals++;return 'new';}}};}
test('concurrent expired reads coalesce renewal and subsequent requests use new SID',async()=>{const f=fixture();await Promise.all([recoverRead(f.args),recoverRead(f.args)]);assert.equal(f.renewals,1);assert.equal(currentSid(f.root,'old'),'new');await recoverRead(f.args);assert.deepEqual(f.calls.at(-1),['new','show-task']);});
test('scripts and mutations are never replayed',async()=>{for(const command of ['run-script','set-host','publish','logout','login']){const f=fixture();await assert.rejects(recoverRead({...f.args,command}),/expired/);assert.equal(f.renewals,0);assert.equal(f.calls.length,1);}});
test('failed renewed read is not retried indefinitely',async()=>{const f=fixture();let attempts=0;await assert.rejects(recoverRead({...f.args,request:async()=>{attempts++;throw Error('expired');}}),/expired/);assert.equal(attempts,2);assert.equal(f.renewals,1);});
test('permission failures do not renew sessions; cancellation prevents recovery',async()=>{const f=fixture();await assert.rejects(recoverRead({...f.args,expired:()=>false}),/expired/);assert.equal(f.renewals,0);await assert.rejects(recoverRead({...f.args,checkCancelled(){throw Error('cancelled');}}),/cancelled/);assert.equal(f.renewals,0);});
test('timing summaries distinguish domains, failures, and renewal context',()=>{const result=summarizeScanTiming([{domain:'A',command:'show-task',status:'ok',durationMs:100},{domain:'B',command:'show-task',status:'failed',durationMs:200},{domain:'B',command:'session-renewal',status:'ok'}]);assert.equal(result.slowestCommands[0].domain,'B');assert.equal(result.domains[1].failures,1);assert.equal(result.sessionRenewals.length,1);});
test('adaptive API queue reduces pressure and recovers only up to configured ceiling',async()=>{const source=readFileSync(new URL('../server.js',import.meta.url),'utf8');const make=vm.runInNewContext(source.slice(source.indexOf('function createLimiter('),source.indexOf('const runScriptQueue'))+';createLimiter');const changes=[];const queue=make(10,{adaptive:true,onChange:c=>changes.push(c)});queue.observe({phase:'timeout'});queue.observe({statusCode:503});assert.equal(changes[0].current,5);assert.equal(changes[1].current,2);for(let i=0;i<300;i++)queue.observe();assert.equal(changes.at(-1).current,10);assert.equal(await queue(()=>42),42);});
