services:
  scanner:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    image: check-point-hardening-app-single-use-public-edition:latest
    container_name: check-point-hardening-app-single-use-public-edition
    init: true
    restart: unless-stopped
    shm_size: "1gb"
    ports:
      - "3100:3100"
    environment:
      HOST: "0.0.0.0"
      PORT: "3100"
      NODE_ENV: "production"
